### ISSUE TITLE
Initial ToDo List

### ISSUE THREAD

**Issue by rushsteve1** [rushsteve1/spinnerette#1]
The first list of things to do in the project

- [ ] Janet Bindings to Go
- [ ] Web Servers
  - [ ] HTTP
  - [ ] FastCGI
  - [ ] CGI
- [ ] Converting Go's `http.Request` to Janet structures like Circle's
- [ ] Static file serving
- [ ] Templates
  - [ ] Go templates
  - [ ] Janet Temple
- [ ] Built in libraries (possibly?)
  - [ ] Spork (required for Temple)
  - [ ] janet-html
  - [ ] Janet SQLite (possibly reimplement in Go)
- [ ] "Managed" SQLite database
- [ ] Dropping permissions to stay within webroot folder
- [ ] Ensure the Janet bindings don't leak memory

**Questions**
- How should Janet files be formatted? A `main` function?
- What should the return value of Janet files be? Should we support multiple kinds? (strings, Janet-HTML arrays)
- How do we properly support shared hosts? Is FastCGI enough?
